version: '3.9'
services:
  quotes:
    build:
      context: ./quotes
    image: quotes:0.1
    container_name: quotes
    ports:
      - 8002:8002
    networks:
     - web
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  newsfeed:
    build:
      context: ./newsfeed
    image: newsfeed:0.1
    container_name: newsfeed
    ports:
      - 8001:8001
    networks:
     - web
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  front-end:
    build:
      context: ./front-end
    image: frontend:0.1
    container_name: frontend
    ports:
      - 8081:8080
      - 8000:8000
    networks:
     - web
    environment:
      NEWSFEED_SERVICE_URL: "http://localhost:8001/api/feeds"
      STATIC_URL: "http://localhost:8000"
      QUOTE_SERVICE_URL: "http://localhost:8002/api/quote"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  haproxy:
    build:
      context: ./haproxy
    image: haproxy:0.1
    container_name: haproxy
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    links:
      - newsfeed
      - quotes
    ports:
      - "80:80"
      - "8404:8404"
    networks:
     - web

networks:
 web:
