apiVersion: v1
kind: Service
metadata:
  labels:
    service: front-end
  name: front-end
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    service: front-end
