apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  labels:
    service: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      service: front-end
  template:
    metadata:
      labels:
        network/web: "true"
        service: front-end
    spec:
      containers:
        - name: frontend
          image: 943618641173.dkr.ecr.us-east-1.amazonaws.com/frontend:latest 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
          env:
            - name: APP_PORT
              value: "8080"
            - name: NEWSFEED_SERVICE_URL
              value: "http://${NEWSFEED_SERVICE_URL}:8001/api/feeds"
            - name: STATIC_URL
              value: "http://${STATIC_URL}:8000"
            - name: QUOTE_SERVICE_URL
              value: "http://${QUOTE_SERVICE_URL}:8002/api/quote"
            - name: NEWSFEED_SERVICE_TOKEN
              value: "T1&eWbYXNWG1w1^YGKDPxAWJ@^et^&kX"
      restartPolicy: Always
