apiVersion: v1
kind: Service
metadata:
  labels:
    service: newsfeed
  name: newsfeed
spec:
  type: ClusterIP
  ports:
    - name: "http"
      port: 8001
      targetPort: 8001
  selector:
    service: newsfeed
