apiVersion: v1
kind: Service
metadata:
  labels:
    service: quote
  name: quote
spec:
  type: ClusterIP
  ports:
    - name: "http"
      port: 8002
      targetPort: 8002
  selector:
    service: quote
